#!/bin/bash

confdir=/etc/kafka
mkdir -p $confdir

: "${KAFKA_ZOOKEEPER_CONNECT:=zk:2181}"
: "${KAFKA_BROKER_ID:=0}"
: "${KAFKA_LOG_DIRS:=/var/lib/kafka/data}"
: "${KAFKA_ADVERTISED_LISTENERS:=PLAINTEXT://localhost:9092,BROKER://${HOSTNAME}:9093}"
: "${KAFKA_LISTENERS:=PLAINTEXT://0.0.0.0:9092,BROKER://0.0.0.0:9093}"
: "${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP:=BROKER:PLAINTEXT,PLAINTEXT:PLAINTEXT}"
: "${KAFKA_INTER_BROKER_LISTENER_NAME:=BROKER}"
: "${KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR:=1}"
: "${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR:=1}"

rm -f $confdir/server.properties
touch $confdir/server.properties
for var in $(compgen -v KAFKA_); do
  prop=$(echo "$var" | sed '
s/^KAFKA_//
s/\([[:alpha:]]\)/\L\1/g
s/_/./g
')
  echo "$prop = ${!var}" >> $confdir/server.properties
done

echo ":::: Using properties ::::"
cat $confdir/server.properties

exec bin/kafka-server-start.sh $confdir/server.properties "$@"



