version: "3"

services:
  zk:
    image: itzg/zookeeper
    volumes:
      - zk:/data
  kafka-0:
    depends_on:
      - zk
    image: itzg/kafka
    environment:
      KAFKA_BROKER_ID: "0"
      KAFKA_ADVERTISED_LISTENERS: "EXTERNAL://localhost:9092,INTERNAL://kafka-0:9093"
    ports:
      - "9092:9092"
    volumes:
      - kafka:/data

volumes:
  zk: {}
  kafka: {}