#!/bin/bash

: "${ZOOKEEPER_CLIENT_PORT:=2181}"
: "${ZOOKEEPER_DATA_DIR:=/var/lib/zookeeper/data}"
: "${ZOOKEEPER_TICK_TIME:=1000}"
: "${ZOOCFGDIR:=/etc/zookeeper}"

# Used by wrapper script
: "${SERVER_JVMFLAGS:=-Xmx256m}"
export SERVER_JVMFLAGS

mkdir -p "$ZOOCFGDIR"
configFile=${ZOOCFGDIR}/zoo.cfg
rm -f $configFile
touch $configFile
for var in $(compgen -v ZOOKEEPER_); do
  prop=$(echo "$var" | sed '
s/^ZOOKEEPER_//
s/\([[:alpha:]]\)/\L\1/g
s/_\([[:alpha:]]\)/\U\1/g
')
  echo "$prop = ${!var}" >> $configFile
done

echo ":::: Using config ::::"
cat "$configFile"

. bin/zkEnv.sh

ZOOMAIN="org.apache.zookeeper.server.quorum.QuorumPeerMain"

cp conf/logback.xml /etc/zookeeper

exec java \
  -XX:+HeapDumpOnOutOfMemoryError -XX:OnOutOfMemoryError='kill -9 %p' \
  -cp \"$CLASSPATH\" $SERVER_JVMFLAGS $ZOOMAIN /etc/zookeeper/zoo.cfg