name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        image:
          - zookeeper
          - kafka
        include:
          - image: kafka
            version_var: KAFKA_VERSION
            version: 3.1.0
          - image: zookeeper
            version_var: ZK_VERSION
            version: 3.8.0
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ github.repository_owner }}/${{ matrix.image }}
          flavor: |
            latest=${{ github.ref_name == 'master' }}
          tags: |
            type=pep440,pattern={{version}},value=${{ matrix.version }}
            type=pep440,pattern={{major}}.{{minor}},value=${{ matrix.version }}
            type=pep440,pattern={{major}},value=${{ matrix.version }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2.9.0
        with:
          context: ${{ matrix.image }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            ${{ matrix.version_var }}=${{ matrix.version }}
          push: ${{ github.ref_type == 'tag' || github.ref_name == 'master' }}
          tags: ${{ steps.meta.outputs.tags }}
          # ensure latest base image is used
          pull: true
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.variant }}
          cache-to: type=gha,mode=max,scope=${{ matrix.variant }}
